image: python:latest
stages:
  - test

test:
  stage: test
  tags:
    - GIO_LAB_CONCURRENT
  # - "jc-cmi"
  # - "rundeck-lab"
  script:
    - echo test
    - echo $(hostname) | mailx -s test harish.krishnoji@fiserv.com
  only:
    - master
