---
stages:
  - master
  - clean

default:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  tags:
    - FTS_LAB_CONCURRENT

master:
  stage: master
  script:
    - docker-compose pull
    - docker-compose up --exit-code-from schema schema
    - docker-compose up --exit-code-from yamllint yamllint
    - curl --request POST "http://rundeck-giolab.1dc.com:4440/api/35/webhook/enJT9CfLPoBA4ORxSeiFvDEb0k5jpFU6#silverline_cicd"

clean:
  stage: clean
  script:
    - docker-compose down --rmi local --remove-orphans --volumes || true
  when: always
