image: python:latest
stages:
  - test

test:
  stage: test
  tags:
    - GIO_LAB_CONCURRENT
  # - "jc-cmi"
  # - "rundeck-lab"
  script:
    - echo test
    - echo $(hostname) | mailx -s test harish.krishnoji@fiserv.com
    - curl --request POST "http://rundeck-giolab.1dc.com:4440/api/35/webhook/enJT9CfLPoBA4ORxSeiFvDEb0k5jpFU6#silverline_cicd"
  only:
    - master
