---
version: "3.8"
services:
  schema:
    command:
      - validate
      - --show-pass
      - --strict
    image: git-enterprise-jc.onefiserv.net:4443/ntc/docker/schema-enforcer:latest
    volumes:
      - ./:/usr/src/app/
  yamllint:
    image: sdesbure/yamllint
    command: yamllint .
    volumes:
      - .:/yaml
  inventory:
    image: ${COMMIT_IMAGE:-local/ddos-denylist-data:latest}
    build:
      context: .
      target: "inventory"
